development:
  adapter: postgresql
  encoding: unicode
  database: chore_manager_dev
  pool: 5
  username: username
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: chore_manager_prod
  pool: 5
  username: username
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: chore_manager_test
  pool: 5
  username: username
  password: password